services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=FeatureFlagDB'
      - 'MYSQL_PASSWORD=user'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=user'
    ports:
      - '3306:3306'
